[package]
name = "sentiric-stream-gateway-service"
version = "0.2.1"
edition = "2021"

[dependencies]
# Async Runtime
tokio = { version = "1.36", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net", "sync"] }
async-stream = "0.3"
futures = "0.3"

# Web & WebSocket
axum = { version = "0.7", features = ["ws", "macros"] }
tower-http = { version = "0.5", features = ["cors", "fs", "trace"] }

# gRPC & Protobuf
tonic = { version = "0.11", features = ["tls", "tls-roots"] }
prost = "0.12"
prost-types = "0.12"

# Data & Config
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
config = "0.14"
uuid = { version = "1.8", features = ["v4", "fast-rng"] }
anyhow = "1.0"
# FIX: Telemetri zaman damgaları için gerekli
chrono = { version = "0.4", features = ["serde"] }

# Observability
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

# Contracts (Git Dependency)
[dependencies.sentiric-contracts]
git = "https://github.com/sentiric/sentiric-contracts.git"
tag = "v1.13.2"

[dev-dependencies]
tokio-tungstenite = "0.20"
url = "2.4"
hound = "3.5"